### ISSUE TITLE
MDTDB module should publish online somewhere like PSGallery, PowerShellGet, NuGet or Chocolatey

### ISSUE THREAD

**Issue by Sharkrit** [vmiller/MDT-Database-script#3]
It would be nice if I can use powershell Import-Module MDTDB from online repository.

**Comment by vmiller** [comment]
You should make that request to Michael Niehaus who wrote the MDTDB Powershell module  : https://blogs.technet.microsoft.com/mniehaus/2009/05/14/manipulating-the-microsoft-deployment-toolkit-database-using-powershell/
