### ISSUE TITLE
New Function Set-MDTComputerIdentity

### ISSUE THREAD

**Issue by genohunter** [vmiller/MDT-Database-script#5]
Hi,

I propose to you this new function : 

Set-MDTComputerIdentity

It's derivated of your function Set-MDTComputer

I don't know why i can't fork and submit my change without UTF16 encoding error that convert file to binarie.

So check my function in attach file. :)

[Set-MDTComputerIdentity.txt](https://github.com/vmiller/MDT-Database-script/files/751598/Set-MDTComputerIdentity.txt)

**Comment by vmiller** [comment]
I too am having trouble adding commits to that file without git thinking it is a binary file.  I'll keep poking at it as time allows.

**Comment by vmiller** [comment]
OK, give this branch a try : https://github.com/vmiller/MDT-Database-script/tree/Set-MDTComputerIdentity

**Comment by genohunter** [comment]
nice :)

**Comment by vmiller** [comment]
Resolved with https://github.com/vmiller/MDT-Database-script/pull/6
