### ISSUE TITLE
Connect-MDTDatabase / Clear-variable "mdtDatabase"

### ISSUE THREAD

**Issue by florianburnel** [vmiller/MDT-Database-script#7]
Hi,

On the line 123 ("_Clear-Variable -name mdtDatabase -errorAction SilentlyContinue_"), when the "mdtDatabase" variable doesn't exist, it return an error (silently). **So, I want to use an error variable with the cmdlet "_Connect-MDTDatabase_" but this line is problematic because there is an error whereas the database connection is OK**.

I suggest that you change this line by : 
` # Clear the results from any previous execution`
 `    if($mdtDatabase){`
	` 	Clear-Variable -name mdtDatabase -errorAction SilentlyContinue`
` }`

What do you think about this ?

Thanks
Florian Burnel
IT-Connect

**Comment by vmiller** [comment]
Yes, seems like this should work.  Do we even need the `-errorAction SilentlyContinue` if we make this change?

**Comment by vmiller** [comment]
Made the suggested change in this branch : https://github.com/vmiller/MDT-Database-script/tree/clear-variable  Can you test it out and let me know how it works for you?

**Comment by florianburnel** [comment]
Hi,

Perfect, the module works with this modification !

Thanks
Florian

**Comment by vmiller** [comment]
I've merged this into the master branch.
